name: Figma Token sync > Supernova
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync_tokens:
    runs-on: ubuntu-latest
    steps:
      # Check out repository under $GITHUB_WORKSPACE, so the CLI utility can read it
      - uses: actions/checkout@v3

      # Setup node to use with CLI. 14+ is required
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      
      # Install Supernova CLI
      - name: Install Supernova CLI dependency
        run: npm install --g @supernovaio/cli

      # Sync tokens
      - name: Synchronize tokens with Supernova 
        run: >
          supernova sync-tokens 
          --apiKey="${{ secrets.SN_ACCESS_TOKEN }}"
          --designSystemId="70580" 
          --tokenFilePath "${{ github.workspace }}/tokens/tokens.json" 
          --configFilePath "${{ github.workspace }}/supernova.settings.json"
